import {
  mkdir,
  readFile,
  rename,
  stat,
  unlink,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { sequenceCatalog } from "../src/data/sequenceCatalog.generated";
import { makeSinglePlayGif, sha256 } from "./singlePlayGif";

const VIDEO_PLAYBACK_VERSION = "single-play-gif-v1";
const VIDEO_REVEAL_DURATION_MS = 31_450;
const EXPECTED_VIDEO_COUNT = 272;

const frontendRoot = fileURLToPath(new URL("../", import.meta.url));
const publicRoot = path.join(frontendRoot, "public");
const generatedModulePath = path.join(
  frontendRoot,
  "src",
  "data",
  "videoPlaybackManifest.generated.ts",
);

interface SourceFingerprint {
  path: string;
  size: number;
  mtimeMs: number;
}

interface PlaybackMetadata {
  presentation_uid: string;
  sequence_uid: string;
  playback_version: typeof VIDEO_PLAYBACK_VERSION;
  source_asset_path: string;
  source_asset_sha256: string;
  playback_asset_path: string;
  playback_asset_sha256: string;
  reveal_duration_ms: typeof VIDEO_REVEAL_DURATION_MS;
  frame_count: number;
  total_duration_ms: number;
  source_loop_count: 0;
  loop_removed: true;
}

function assertSafeRelativeAssetPath(assetPath: string): void {
  const normalized = assetPath.replaceAll("\\", "/");
  if (
    normalized !== assetPath ||
    path.posix.isAbsolute(normalized) ||
    normalized.startsWith("../") ||
    normalized.includes("/../") ||
    !normalized.startsWith("assets/")
  ) {
    throw new Error(`Unsafe catalog asset path: ${assetPath}`);
  }
}

async function writeFileAtomicallyIfChanged(
  filename: string,
  content: Buffer | string,
): Promise<boolean> {
  const bytes = typeof content === "string" ? Buffer.from(content) : content;
  try {
    const existing = await readFile(filename);
    if (existing.equals(bytes)) {
      return false;
    }
  } catch (error) {
    if (
      !(error instanceof Error) ||
      !("code" in error) ||
      error.code !== "ENOENT"
    ) {
      throw error;
    }
  }

  await mkdir(path.dirname(filename), { recursive: true });
  const temporaryFilename =
    `${filename}.tmp-${process.pid}-${Math.random().toString(16).slice(2)}`;
  await writeFile(temporaryFilename, bytes, { flag: "wx" });
  try {
    await rename(temporaryFilename, filename);
  } catch (error) {
    if (
      error instanceof Error &&
      "code" in error &&
      (error.code === "EEXIST" || error.code === "EPERM")
    ) {
      await unlink(filename);
      await rename(temporaryFilename, filename);
    } else {
      throw error;
    }
  }
  return true;
}

function renderGeneratedModule(
  entries: readonly PlaybackMetadata[],
): string {
  const objectLines = entries.map(
    (entry) =>
      `  ${JSON.stringify(entry.presentation_uid)}: ` +
      `${JSON.stringify(entry)},`,
  );

  return `/* AUTO-GENERATED by scripts/generate-single-play-gifs.ts. */
/* Do not edit by hand. Original research GIFs remain unchanged. */

export const VIDEO_PLAYBACK_VERSION = ${JSON.stringify(VIDEO_PLAYBACK_VERSION)} as const;
export const VIDEO_REVEAL_DURATION_MS = 31_450 as const;

export interface VideoPlaybackMetadata {
  readonly presentation_uid: string;
  readonly sequence_uid: string;
  readonly playback_version: typeof VIDEO_PLAYBACK_VERSION;
  readonly source_asset_path: string;
  readonly source_asset_sha256: string;
  readonly playback_asset_path: string;
  readonly playback_asset_sha256: string;
  readonly reveal_duration_ms: typeof VIDEO_REVEAL_DURATION_MS;
  readonly frame_count: number;
  readonly total_duration_ms: number;
  readonly source_loop_count: 0;
  readonly loop_removed: true;
}

export const videoPlaybackManifestByPresentationUid = {
${objectLines.join("\n")}
} as const satisfies Readonly<Record<string, VideoPlaybackMetadata>>;

export type VideoPlaybackPresentationUid =
  keyof typeof videoPlaybackManifestByPresentationUid;

export function getVideoPlaybackMetadata(
  presentationUid: string,
): VideoPlaybackMetadata {
  const metadata = (
    videoPlaybackManifestByPresentationUid as
      Readonly<Record<string, VideoPlaybackMetadata>>
  )[presentationUid];
  if (!metadata) {
    throw new Error(
      \`Missing single-play GIF metadata for presentation \${presentationUid}\`,
    );
  }
  return metadata;
}
`;
}

async function main(): Promise<void> {
  if (sequenceCatalog.length !== EXPECTED_VIDEO_COUNT) {
    throw new Error(
      `Expected ${EXPECTED_VIDEO_COUNT} catalog sequences, found ` +
        `${sequenceCatalog.length}`,
    );
  }

  const sourceFingerprints: SourceFingerprint[] = [];
  const entries: PlaybackMetadata[] = [];
  const presentationUids = new Set<string>();
  const sequenceUids = new Set<string>();
  const playbackPaths = new Set<string>();

  for (const sequence of sequenceCatalog) {
    const presentation = sequence.presentations.video;
    assertSafeRelativeAssetPath(presentation.legacy_path);

    if (!presentationUids.add(presentation.presentation_uid)) {
      throw new Error(
        `Duplicate Video presentation UID: ${presentation.presentation_uid}`,
      );
    }
    if (!sequenceUids.add(sequence.sequence_uid)) {
      throw new Error(`Duplicate sequence UID: ${sequence.sequence_uid}`);
    }

    const sourcePath = path.join(
      publicRoot,
      ...presentation.legacy_path.split("/"),
    );
    const sourceStat = await stat(sourcePath);
    sourceFingerprints.push({
      path: sourcePath,
      size: sourceStat.size,
      mtimeMs: sourceStat.mtimeMs,
    });

    const sourceBytes = await readFile(sourcePath);
    const sourceAssetSha256 = sha256(sourceBytes);
    if (sourceAssetSha256 !== presentation.asset_sha256) {
      throw new Error(
        `${sequence.sequence_uid}: source GIF hash mismatch; catalog has ` +
          `${presentation.asset_sha256}, file has ${sourceAssetSha256}`,
      );
    }

    const result = makeSinglePlayGif(sourceBytes);
    const { sourceInspection, derivedInspection } = result;
    if (sourceInspection.frameCount !== presentation.gif_frame_count) {
      throw new Error(
        `${sequence.sequence_uid}: expected ${presentation.gif_frame_count} ` +
          `frames, parsed ${sourceInspection.frameCount}`,
      );
    }
    if (
      sourceInspection.totalDurationMs !==
      presentation.gif_total_duration_ms
    ) {
      throw new Error(
        `${sequence.sequence_uid}: expected total duration ` +
          `${presentation.gif_total_duration_ms}ms, parsed ` +
          `${sourceInspection.totalDurationMs}ms`,
      );
    }
    if (presentation.gif_loop !== 0) {
      throw new Error(
        `${sequence.sequence_uid}: catalog source loop count is not 0`,
      );
    }
    if (
      sourceInspection.finalFrameOnsetMs !==
      VIDEO_REVEAL_DURATION_MS
    ) {
      throw new Error(
        `${sequence.sequence_uid}: expected final-frame onset ` +
          `${VIDEO_REVEAL_DURATION_MS}ms, parsed ` +
          `${sourceInspection.finalFrameOnsetMs}ms`,
      );
    }

    const playbackAssetPath =
      `assets/video-single-play-v1/${sequence.sequence_uid}.gif`;
    if (!playbackPaths.add(playbackAssetPath)) {
      throw new Error(`Duplicate derived playback path: ${playbackAssetPath}`);
    }
    entries.push({
      presentation_uid: presentation.presentation_uid,
      sequence_uid: sequence.sequence_uid,
      playback_version: VIDEO_PLAYBACK_VERSION,
      source_asset_path: presentation.legacy_path,
      source_asset_sha256: sourceAssetSha256,
      playback_asset_path: playbackAssetPath,
      playback_asset_sha256: sha256(result.bytes),
      reveal_duration_ms: VIDEO_REVEAL_DURATION_MS,
      frame_count: derivedInspection.frameCount,
      total_duration_ms: derivedInspection.totalDurationMs,
      source_loop_count: 0,
      loop_removed: true,
    });
  }

  entries.sort((left, right) =>
    left.presentation_uid.localeCompare(right.presentation_uid, "en"),
  );
  const moduleChanged = await writeFileAtomicallyIfChanged(
    generatedModulePath,
    renderGeneratedModule(entries),
  );

  for (const fingerprint of sourceFingerprints) {
    const after = await stat(fingerprint.path);
    if (
      after.size !== fingerprint.size ||
      after.mtimeMs !== fingerprint.mtimeMs
    ) {
      throw new Error(
        `Original research GIF changed during generation: ${fingerprint.path}`,
      );
    }
  }

  console.log(
    `Single-play GIF manifest generation passed: ${entries.length} assets; ` +
      `generated module ${moduleChanged ? "updated" : "unchanged"}; ` +
      `no derived GIFs were persisted outside the build output.`,
  );
}

await main();
